apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: saas-template

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - server-deployment.yaml
  - web-deployment.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: saas-template

images:
  - name: saas-template/server
    newTag: latest
  - name: saas-template/web
    newTag: latest
