name: saas-template

services:
  postgres:
    image: postgres
    container_name: saas-template-postgres
    environment:
      POSTGRES_DB: saas-template
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - saas-template_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  saas-template_postgres_data:
